Allow Meraki Filter by Network and Org
kentik/ktranslate pull request #410
Opened 2022-08-29 21:11 UTC by i3149

Given a device config like:

```
  meraki_cloud_controller:
    device_name: meraki_cloud_controller
    device_ip: snmp.meraki.com
    ext:
      ext_only: true
      meraki_config:
        api_key: my-meraki-api-key
        networks:
          - "Network 1"
          - "Network 2"
        organizations:
          - "Org 1"
```

This PR allows only the specified networks and organizations to be polled.

2022-09-09 18:56 UTC, thezackm commented on pkg/inputs/snmp/x/meraki/meraki.go
> +				"mdsn_name":          client.MdnsName,
should be `mdns_name`

2022-09-09 18:58 UTC, thezackm requested changes

2022-09-09 18:58 UTC, thezackm commented on pkg/inputs/snmp/x/meraki/meraki.go
> +				"mdsn_name":          client.MdnsName,
should be `mdns_name`

2022-09-09 21:05 UTC, jbeveland27 approved these changes

2022-09-22 16:22 UTC, thezackm approved these changes

2022-09-22 16:23 UTC, merged